### ISSUE TITLE
Make clash cards look better

### ISSUE THREAD

**Issue by Andriamanitra** [Andriamanitra/clash-search#12]
Clash cards (in frontend/src/lib/ClashCard.svelte) are rather hastily put together. The paddings and margins are all over the place and the colors could be improved.

## Tasks: 
- [ ] Use a different background color for input/output boxes
- [ ] Fix the large and weird gaps around titles in the "Details" view
- [ ] Use a couple different text colors to highlight important bits and provide clearer visual separation between titles and body text (may need to adjust app.css of the whole site)
- [ ] Make all of the above work nicely in both light and dark mode

Pull requests are welcome, not sure when I'll have time to get to this issue myself...
