### ISSUE TITLE
Add regular puzzle search

### ISSUE THREAD

**Issue by Andriamanitra** [Andriamanitra/clash-search#3]
Currently the system is only indexing Clash of Code puzzles. The old puzzle search could also be used for regular in/out puzzles. Although this feature is probably less used than the clash search, it should not be much work to add because the JSON structure of in/out puzzles is very similar (maybe even identical?) to clashes.

## TODO:
* [ ] Update fetch script to check for new in/out puzzles too and store them on disk
* [ ] Make sure they are added to MeiliSearch and it is correctly indexing them
* [ ] Add a way to toggle which puzzles (clashes or in/out puzzles or both) are searched on the web page
* [ ] Update README
